name: CI

on:
  push:
  release:
    types: [published]

env:
  TOIT_VERSION: v2.0.0-alpha.100

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: toitlang/action-setup@v1
        with:
          toit-version: ${{ env.TOIT_VERSION }}

      - name: Test
        run: |
          make test
